/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package io.github.usafa_compsci350;

class AppTest {
  public static void main(String[] args) {
    new CityInfoTest(); //Test CityInfo class
    new IntroWindowTest(); //Test the Intro Window
    new LogFunctionTest(); //Test Log Function
    new MainWindowTest(); //test main window operation
    new ReadCityTest(); //test city excel file parsing
    new ReadNetworkTest(); //test network text file parsing
  }
}
